### ISSUE TITLE
Suggested change in the README file 

### ISSUE THREAD

**Issue by dorzheh** [openshift-kni/cnf-features-deploy#75]
In the file, https://github.com/openshift-kni/cnf-features-deploy/blob/master/README.md appears that  _FEATURES_ENVIRONMENT=demo make functests is_ the command for executing the relevant tests.
However, it seems the correct command is  _FEATURES=test1 test2 testN make functests_

**Comment by fedepaol** [comment]
Ah thanks!
Will change that.

**Comment by slintes** [comment]
we have both `FEATURES_ENVIRONMENT` and `FEATURES`, and both have defaults set on top of the `Makefile` [0].
The default for `FEATURES_ENVIRONMENT` is the CI config override directory (`e2e-gcp`), that's why we override it in the readme to the `demo` dir.
But I agree that it makes sense to mention that you can also override `FEATURES` :+1: 

[0] https://github.com/openshift-kni/cnf-features-deploy/blob/master/Makefile

**Comment by fedepaol** [comment]
> we have both `FEATURES_ENVIRONMENT` and `FEATURES`, and both have defaults set on top of the `Makefile` [0].
> The default for `FEATURES_ENVIRONMENT` is the CI config override directory (`e2e-gcp`), that's why we override it in the readme to the `demo` dir.
> But I agree that it makes sense to mention that you can also override `FEATURES` +1
> 
> [0] https://github.com/openshift-kni/cnf-features-deploy/blob/master/Makefile

Yes, but the point is, in [testing](https://github.com/openshift-kni/cnf-features-deploy/blob/master/README.md#testing) we suggest to set `FEATURES_ENVIRONMENT` which does not make sense there.

**Comment by slintes** [comment]
fixed in #76 

/close
